FROM centos:7
RUN  yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
RUN yum install ansible -y
RUN yum install git -y
WORKDIR /etc/ansible/
RUN git pull https://github.com/vallenjr11/project21/tree/master/ansible


